### ISSUE TITLE
Develop the table of DH parameters

### ISSUE THREAD

**Issue by Lovndir** [Lovndir/ele306_semesteroppgave#2]

**Comment by CaptainBersun** [comment]
so it is, that we find ourselves at the edge of the abyss. shall we fall in, forever lost, never to be heard from again? or shall we step away, walking towards the light?

**Comment by AudunGjersvik** [comment]
Hei, får ikke til å dele matlab live script fil på dette...
men trur hovedsakerlig at DH parameterne skal defineres noe slik som dette: 
syms a1 a2 a3 a4 a5 a6 q1 q2 q3 q4 q5 q6
L(1) = Link([0 0 a1 0]);
L(2) = Link([0 0 a2 0]);
L(3) = Link([0 0 a3 0]);
L(4) = Link([0 0 a4 0]);
L(5) = Link([0 0 a5 0]);
L(6) = Link([0 0 a6 0]);
arm_A=SerialLink(L,'name','My Robot')
arm_A.fkine([q1 q2 q3 q4 q5 q6])

**Comment by AudunGjersvik** [comment]
var mye robotikk teori rundt dette, og trur dette forslaget må selv endres på etter hvert som vi kommer videre, som sagt dette er bare oppsett til 1 robotarm, ikke 2 skal se på dette videre
